apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-processor
  labels:
    app: message-processor
    tier: worker
    lang: go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: message-processor
  template:
    metadata:
      labels:
        app: message-processor
        tier: worker
        lang: go
    spec:
      containers:
      - name: message-processor
        image: message-processor:latest
        imagePullPolicy: Never
        env:
        - name: MESSAGE_BROKER
          value: "kafka"
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq:5672/"
        - name: DB_HOST
          value: "postgresql"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_NAME
          value: "queue_case"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: message-processor
  labels:
    app: message-processor
    tier: worker
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: message-processor

